### ISSUE TITLE
 TypeError: __init() got an unexpected keyword argument 'use_wheel'

### ISSUE THREAD

**Issue by mahinthjoe** [erikrose/peep#101]
---
peep: (2, 3, 0)
python: '2.7.6 (default, Sep  9 2014, 15:04:36) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)]'
pip: '7.0.3'
Command line:  ['bin/peep.py', 'install', '-r', 'requirements/dev.txt']
Traceback (most recent call last):
  File "bin/peep.py", line 899, in <module>
    exit(main())
  File "bin/peep.py", line 871, in main
    return commands[argv[1]](argv[2:])
  File "bin/peep.py", line 831, in peep_install
    for path in req_paths))
  File "bin/peep.py", line 831, in <genexpr>
    for path in req_paths))
  File "bin/peep.py", line 808, in downloaded_reqs_from_path
    path, options=EmptyOptions(), session=PipSession()))
  File "bin/peep.py", line 797, in downloaded_reqs
    return [DownloadedReq(req, argv) for req in parsed_reqs]
  File "bin/peep.py", line 366, in __init__
    self.__class__ = self._class()
  File "bin/peep.py", line 673, in _class
    if self._actual_hash() not in self._expected_hashes():
  File "bin/peep.py", line 278, in memoizer
    self._cache[func.__name__] = func(self)
  File "bin/peep.py", line 629, in _actual_hash
    return hash_of_file(join(self._temp_path, self._downloaded_filename()))
  File "bin/peep.py", line 278, in memoizer
    self._cache[func.__name__] = func(self)
  File "bin/peep.py", line 578, in _downloaded_filename
    finder = package_finder(self._argv)
  File "bin/peep.py", line 335, in package_finder
    return PackageFinder(index_urls=index_urls, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_wheel'

---

**Comment by willkg** [comment]
This is a repeat of issue #96. Closing it out.
