### ISSUE TITLE
'use_wheel' argument error during requirement installation

### ISSUE THREAD

**Issue by Sid-Shanker** [erikrose/peep#105]
I was trying to install the requirements and got error. Installed wheel version is 0.24. Here is the bug report: 
---
peep: (2, 4, 0)
python: '2.7.6 (default, Mar 22 2014, 22:59:56) \n[GCC 4.8.2]'
pip: '7.1.2'
Command line:  ['./scripts/peep.py', 'install', '-r', 'requirements/default.txt']
Traceback (most recent call last):
  File "./scripts/peep.py", line 902, in <module>
    exit(main())
  File "./scripts/peep.py", line 874, in main
    return commands[argv[1]](argv[2:])
  File "./scripts/peep.py", line 834, in peep_install
    for path in req_paths))
  File "./scripts/peep.py", line 834, in <genexpr>
    for path in req_paths))
  File "./scripts/peep.py", line 795, in downloaded_reqs_from_path
    finder = package_finder(argv)
  File "./scripts/peep.py", line 335, in package_finder
    return PackageFinder(index_urls=index_urls, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'use_wheel'

---

**Comment by Natim** [comment]
Same problem here, which version of pip should I use with peep 2.4.1?

**Comment by erikrose** [comment]
Anything less than pip 7 will work. I've ported peep functionality into pip 8, so we can all look forward to that early next year. :-)
