### ISSUE TITLE
No handlers could be found for logger "pip.index"

### ISSUE THREAD

**Issue by edmorley** [erikrose/peep#108]
Seen on this Travis run:
https://travis-ci.org/mozilla/treeherder/builds/83169943

The error is real (the author had removed that version of their package from PyPI for some reason), but it should be printed out to the console and not result in an exception.

```
0.49s$ ./bin/peep.py install -r requirements/common.txt -r requirements/dev.txt
Downloading mohawk==0.3.0 (12K)...
  100% |################################| 16kB 19.1MB/s 
No handlers could be found for logger "pip.index"
Oh no! Peep had a problem while trying to do stuff. Please write up a bug report
with the specifics so we can fix it:
https://github.com/erikrose/peep/issues/new
Here are some particulars you can copy and paste into the bug report:
---
peep: (2, 4, 1)
python: '2.7.9 (default, Feb  5 2015, 15:48:42) \n[GCC 4.6.3]'
pip: '6.0.7'
Command line:  ['./bin/peep.py', 'install', '-r', 'requirements/common.txt', '-r', 'requirements/dev.txt']
Traceback (most recent call last):
  File "./bin/peep.py", line 901, in <module>
    exit(main())
  File "./bin/peep.py", line 873, in main
    return commands[argv[1]](argv[2:])
  File "./bin/peep.py", line 833, in peep_install
    for path in req_paths))
  File "./bin/peep.py", line 833, in <genexpr>
    for path in req_paths))
  File "./bin/peep.py", line 810, in downloaded_reqs_from_path
    path, options=EmptyOptions(), session=PipSession(), finder=finder))
  File "./bin/peep.py", line 798, in downloaded_reqs
    return [DownloadedReq(req, argv, finder) for req in parsed_reqs]
  File "./bin/peep.py", line 367, in __init__
    self.__class__ = self._class()
  File "./bin/peep.py", line 672, in _class
    if self._actual_hash() not in self._expected_hashes():
  File "./bin/peep.py", line 278, in memoizer
    self._cache[func.__name__] = func(self)
  File "./bin/peep.py", line 628, in _actual_hash
    return hash_of_file(join(self._temp_path, self._downloaded_filename()))
  File "./bin/peep.py", line 278, in memoizer
    self._cache[func.__name__] = func(self)
  File "./bin/peep.py", line 581, in _downloaded_filename
    link = self._link() or self._finder.find_requirement(self._req, upgrade=False)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/pip/index.py", line 490, in find_requirement
    'No distributions matching the version for %s' % req
DistributionNotFound: No distributions matching the version for hawkrest==0.0.6 (from -r requirements/common.txt (line 125))
```

**Comment by edmorley** [comment]
The exception here is fixed by #118, though the `No handlers could be found for logger "pip.index"` output is not. I've tried adding a log handler to peep to avoid it, however the resultant output is fairly spammy, even when limiting it to CRITICAL log level only:
```
[~/src/peep]$ ./peep.py install -r ../test1.txt
/usr/lib/python2.7/site-packages/pip/req/req_install.py:1007: UserWarning: Unbuilt egg for peep [unknown version] (/home/Ed/src/peep)
  self.satisfied_by = pkg_resources.get_distribution(self.req)
CRITICAL:pip.index:Could not find a version that satisfies the requirement kjnkjnkjnkjn==99999 (from -r ../test1.txt (line 1)) (from versions: )

The following packages had no hashes specified in the requirements file, which
leaves them open to tampering. Vet these packages to your satisfaction, then
add these "sha256" lines like so:

No matching distribution found for kjnkjnkjnkjn==99999 (from -r ../test1.txt (line 1))
```
The other option would be to add a `NullHandler`, however that doesn't exist in Python 2.6, so requires a fallback:
http://docs.python-guide.org/en/latest/writing/logging/#logging-in-a-library

I don't think it's worth the effort to be honest -- and arguably pip should perhaps add a NullHandler itself to avoid the warnings in the first place.
