### ISSUE TITLE
DistributionNotFound: No distributions at all found for Werkzeug==0.11.3 (from -r /tmp/tmp.YadJ1nkN9L/letsencrypt-auto-requirements.txt (line 177))

### ISSUE THREAD

**Issue by saleo** [erikrose/peep#121]
peep: (3, 0, 0)
python: '2.6.6 (r266:84292, Jul 23 2015, 15:22:56) \n[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)]'
pip: '1.4.1'
Command line:  ['/tmp/tmp.YadJ1nkN9L/peep.py', 'install', '-r', '/tmp/tmp.YadJ1nkN9L/letsencrypt-auto-requirements.txt']
Traceback (most recent call last):
  File "/tmp/tmp.YadJ1nkN9L/peep.py", line 958, in <module>
    exit(main())
  File "/tmp/tmp.YadJ1nkN9L/peep.py", line 930, in main
    return commands[argv[1]](argv[2:])
  File "/tmp/tmp.YadJ1nkN9L/peep.py", line 862, in peep_install
    for path in req_paths))
  File "/tmp/tmp.YadJ1nkN9L/peep.py", line 862, in <genexpr>
    for path in req_paths))
  File "/tmp/tmp.YadJ1nkN9L/peep.py", line 839, in downloaded_reqs_from_path
    _parse_requirements(path, finder)]
  File "/tmp/tmp.YadJ1nkN9L/peep.py", line 420, in __init__
    self.__class__ = self._class()
  File "/tmp/tmp.YadJ1nkN9L/peep.py", line 699, in _class
    if self._actual_hash() not in self._expected_hashes():
  File "/tmp/tmp.YadJ1nkN9L/peep.py", line 329, in memoizer
    self._cache[func.__name__] = func(self)
  File "/tmp/tmp.YadJ1nkN9L/peep.py", line 655, in _actual_hash
    return hash_of_file(join(self._temp_path, self._downloaded_filename()))
  File "/tmp/tmp.YadJ1nkN9L/peep.py", line 329, in memoizer
    self._cache[func.__name__] = func(self)
  File "/tmp/tmp.YadJ1nkN9L/peep.py", line 608, in _downloaded_filename
    link = self._link() or self._finder.find_requirement(self._req, upgrade=False)
  File "/root/.local/share/letsencrypt/lib/python2.6/site-packages/pip/index.py", line 265, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
DistributionNotFound: No distributions at all found for Werkzeug==0.11.3 (from -r /tmp/tmp.YadJ1nkN9L/letsencrypt-auto-requirements.txt (line 177))

**Comment by saleo** [comment]
the above info. comes from cloud host , centOS 6.7,x64

**Comment by edmorley** [comment]
Hi :-)

This isn't an issue with peep, but an error returned by pip:
`DistributionNotFound: No distributions at all found for Werkzeug==0.11.3 (from -r /tmp/tmp.YadJ1nkN9L/letsencrypt-auto-requirements.txt (line 177))`

Unfortunately peep hasn't handled that error well, and as such mistakenly displayed the message asking you to file a ticket. #118 has fixed peep so it doesn't mislead, however we're waiting on letsencrypt/letsencrypt#2486 to update letsencrypt-auto to use this fixed version of peep.

I'd try running letsencrypt-auto again, and failing that try checking if pip works on its own on that box.

**Comment by erikrose** [comment]
I'm trying to nudge us to get Let's Encrypt 0.4.1 out the door soon. :-)

**Comment by saleo** [comment]
resolved by upgrade python from 2.6 to 2.7, 8=)
