### ISSUE TITLE
Just had this error when trying to use with Letsencrypt 

### ISSUE THREAD

**Issue by dragonsvape** [erikrose/peep#141]
peep: (3, 1, 1)
python: '2.7.11 (default, Dec  7 2015, 11:26:11) \n[GCC 4.4.7 20120313 (Red Hat                                                                                         4.4.7-16)]'
pip: '1.4.1'
Command line:  ['/tmp/tmp.a9J1RVvxD4/peep.py', 'install', '-r', '/tmp/tmp.a9J1RV                                                                                        vxD4/letsencrypt-auto-requirements.txt']
Traceback (most recent call last):
  File "/tmp/tmp.a9J1RVvxD4/peep.py", line 967, in <module>
    exit(main())
  File "/tmp/tmp.a9J1RVvxD4/peep.py", line 939, in main
    return commands[argv[1]](argv[2:])
  File "/tmp/tmp.a9J1RVvxD4/peep.py", line 884, in peep_install
    req.install()
  File "/tmp/tmp.a9J1RVvxD4/peep.py", line 652, in install
    run_pip(['install'] + other_args + ['--no-deps', '-U', archive_path])
  File "/tmp/tmp.a9J1RVvxD4/peep.py", line 206, in run_pip
    status_code = pip.main(initial_args)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/__init__.                                                                                        py", line 148, in main
    return command.main(args[1:], options)
  File "/root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/basecomma                                                                                        nd.py", line 169, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 36: ordinal                                                                                         not in range(128)

**Comment by Questra1998wwert** [comment]
"/Root/.local/share/letsencrypt/lib/python2.7/site-packages/pip/basecomma nd.py"

**Comment by erikrose** [comment]
Sorry you had trouble. Peep is no longer necessary, since its functionality has been rolled into pip, as of pip version 8. Please see the docs at https://pip.pypa.io/en/stable/topics/secure-installs/#hash-checking-mode, and happy hashing!
