### ISSUE TITLE
Support for '--extra-index-url/--index-url' in requirements.txt

### ISSUE THREAD

**Issue by rouge8** [erikrose/peep#70]
pip supports specifying the `--extra-index-url`/`--index-url` options in a requirements.txt file, e.g.

```
--index-url=https://our-internal-package-server.com/pypi/
# sha256: f11aEB33vl31Rw53uFAN_govGddZgkWBScQHEfg9Q4w
custom-package==1.0.1
```

However, attempting to install this with peep fails:

```console
$ peep install -r requirements.txt
No handlers could be found for logger "pip.index"

Traceback (most recent call last):
  File "/Users/rouge8/.virtualenvs/tmp-f31839f7ea06217/bin/peep", line 9, in <module>
    load_entry_point('peep==2.1', 'console_scripts', 'peep')()
  File "/Users/rouge8/.virtualenvs/tmp-f31839f7ea06217/lib/python2.7/site-packages/peep.py", line 811, in main
    return commands[argv[1]](argv[2:])
  File "/Users/rouge8/.virtualenvs/tmp-f31839f7ea06217/lib/python2.7/site-packages/peep.py", line 771, in peep_install
    for path in req_paths))
  File "/Users/rouge8/.virtualenvs/tmp-f31839f7ea06217/lib/python2.7/site-packages/peep.py", line 771, in <genexpr>
    for path in req_paths))
  File "/Users/rouge8/.virtualenvs/tmp-f31839f7ea06217/lib/python2.7/site-packages/peep.py", line 747, in downloaded_reqs_from_path
    session=PipSession())]
  File "/Users/rouge8/.virtualenvs/tmp-f31839f7ea06217/lib/python2.7/site-packages/peep.py", line 340, in __init__
    self.__class__ = self._class()
  File "/Users/rouge8/.virtualenvs/tmp-f31839f7ea06217/lib/python2.7/site-packages/peep.py", line 615, in _class
    if self._actual_hash() not in self._expected_hashes():
  File "/Users/rouge8/.virtualenvs/tmp-f31839f7ea06217/lib/python2.7/site-packages/peep.py", line 252, in memoizer
    self._cache[func.__name__] = func(self)
  File "/Users/rouge8/.virtualenvs/tmp-f31839f7ea06217/lib/python2.7/site-packages/peep.py", line 580, in _actual_hash
    return hash_of_file(join(self._temp_path, self._downloaded_filename()))
  File "/Users/rouge8/.virtualenvs/tmp-f31839f7ea06217/lib/python2.7/site-packages/peep.py", line 252, in memoizer
    self._cache[func.__name__] = func(self)
  File "/Users/rouge8/.virtualenvs/tmp-f31839f7ea06217/lib/python2.7/site-packages/peep.py", line 535, in _downloaded_filename
    if self._req.url is None
  File "/Users/rouge8/.virtualenvs/tmp-f31839f7ea06217/lib/python2.7/site-packages/pip/index.py", line 397, in find_requirement
    'No distributions at all found for %s' % req
pip.exceptions.DistributionNotFound: No distributions at all found for custom-package==1.0.1
 (from -r requirements.txt (line 9))
```

**Comment by rouge8** [comment]
It looks like pip supports a few other options in `requirements.txt` as well: https://github.com/pypa/pip/blob/develop/pip/req/req_file.py

**Comment by erikrose** [comment]
Those options are parsed by pip's own parse_requirements(), which we still call. Unfortunately, we're throwing what it extracts on the floor. We should be constructing our PackageFinder first, then passing it to parse_requirements() so it can scribble the specified options on it. We should probably also be passing some or all of the commandline options to parse_requirements as the `options` kwarg, but that's a separate issue.
