### ISSUE TITLE
[traceback] AttributeError: 'NoneType' object has no attribute 'url'

### ISSUE THREAD

**Issue by edmorley** [erikrose/peep#80]
pip v6.1.1 has just been released:
https://pip.pypa.io/en/latest/news.html

This seems to have broken peep:
```bash
(temp1234)[~/src/treeherder-service]$ pip --version
pip 6.1.1 from C:\Users\Ed\.virtualenvs\temp1234\lib\site-packages (python 2.7)
(temp1234)[~/src/treeherder-service]$ ./bin/peep.py install -r requirements/common.txt

Oh no! Peep had a problem while trying to do stuff. Please write up a bug report
with the specifics so we can fix it:

https://github.com/erikrose/peep/issues/new

Here are some particulars you can copy and paste into the bug report:

---
peep: (2, 2, 0)
python: '2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)]'
pip: '6.1.1'
Command line:  ['./bin/peep.py', 'install', '-r', 'requirements/common.txt']
Traceback (most recent call last):
  File "./bin/peep.py", line 896, in <module>
    exit(main())
  File "./bin/peep.py", line 868, in main
    return commands[argv[1]](argv[2:])
  File "./bin/peep.py", line 828, in peep_install
    for path in req_paths))
  File "./bin/peep.py", line 828, in <genexpr>
    for path in req_paths))
  File "./bin/peep.py", line 805, in downloaded_reqs_from_path
    path, options=EmptyOptions(), session=PipSession()))
  File "./bin/peep.py", line 794, in downloaded_reqs
    return [DownloadedReq(req, argv) for req in parsed_reqs]
  File "./bin/peep.py", line 371, in __init__
    self.__class__ = self._class()
  File "./bin/peep.py", line 670, in _class
    if self._actual_hash() not in self._expected_hashes():
  File "./bin/peep.py", line 283, in memoizer
    self._cache[func.__name__] = func(self)
  File "./bin/peep.py", line 635, in _actual_hash
    return hash_of_file(join(self._temp_path, self._downloaded_filename()))
  File "./bin/peep.py", line 283, in memoizer
    self._cache[func.__name__] = func(self)
  File "./bin/peep.py", line 587, in _downloaded_filename
    if self._req.url is None
  File "C:\Users\Ed\.virtualenvs\temp1234\lib\site-packages\pip\req\req_install.py", line 128, in url
    return self.link.url
AttributeError: 'NoneType' object has no attribute 'url'
````

**Comment by edmorley** [comment]
Local testing showed pip 6.0.8 to work and 6.1.0 to fail, giving a regression range of:
https://github.com/pypa/pip/compare/6.0.8...6.1.0

The following look to be relevant:
https://github.com/pypa/pip/commit/e8e2566279879b7df04394edfcaa9c63c0ce9e67
https://github.com/pypa/pip/commit/66c1d3bb6a9306f0f5cb9724230f84a299aa49eb

**Comment by edmorley** [comment]
I've also submitted a PR against pip to fix their shim: https://github.com/pypa/pip/pull/2655

**Comment by willkg** [comment]
^^^ Fixed the summary so it matches the issue.
